<?php

declare(strict_types=1);

return [
  'aero' => true,
  'bank' => true,
  'coop' => true,
  'creditunion' => true,
  'insurance' => true,
  'int' => true,
  'pharmacy' => true,
  'post' => true,
  'museum' => true,
  'resbank' => true,

  // Academic and Educational Entities
  'ac.at' => true, //  Austria
  'ac.bd' => true, //  Bangladesh
  'ac.be' => true, //  Belgium
  'ac.bw' => true, //  Botswana
  'ac.cn' => true, //  China
  'ac.cr' => true, //  Costa Rica
  'ac.cy' => true, //  Cyprus
  'ac.fj' => true, //  Fiji
  'ac.in' => true, //  India
  'ac.id' => true, //  Indonesia
  'ac.ir' => true, //  Iran
  'ac.il' => true, //  Israel
  'ac.jp' => true, //  Japan
  'ac.ke' => true, //  Kenya
  'ac.ma' => true, //  Morocco
  'ac.nz' => true, //  New Zealand
  'ac.kp' => true, //  North Korea
  'aca.kp' => true, //  North Korea
  'ac.pg' => true, //  Papua New Guinea
  'ac.rw' => true, //  Rwanda
  'ac.rs' => true, //  Serbia
  'ac.za' => true, //  South Africa
  'ac.kr' => true, //  South Korea
  'ac.ss' => true, //  South Sudan
  'ac.lk' => true, //  Sri Lanka
  'ac.tz' => true, //  Tanzania
  'ac.th' => true, //  Thailand
  'ac.ug' => true, //  Uganda
  'ac.uk' => true, //  United Kingdom
  'ac.ae' => true, //  United Arab Emirates
  'ac.zm' => true, //  Zambia
  'ac.zw' => true, //  Zimbabwe

  'edu' => true, //  America
  'edu.ag' => true, //  Antigua & Barbuda
  'edu.ar' => true, //  Argentina
  'edu.au' => true, //  Australia
  'edu.az' => true, //  Azerbaijan
  'edu.bd' => true, //  Bangladesh
  'edu.br' => true, //  Brazil
  'edu.bn' => true, //  Brunei
  'edu.cn' => true, //  China
  'edu.co' => true, //  Colombia
  'edu.dj' => true, //  Djibouti
  'edu.ec' => true, //  Ecuador
  'edu.eg' => true, //  Egypt
  'edu.sv' => true, //  El Salvador
  'edu.er' => true, //  Eritrea
  'edu.ee' => true, //  Estonia
  'edu.et' => true, //  Ethiopia
  'edu.fi' => true, //  Finland
  'edu.gh' => true, //  Ghana
  'edu.gr' => true, //  Greece
  'edu.gt' => true, //  Guatemala
  'edu.hk' => true, //  Hong Kong
  'edu.it' => true, //  Italy
  'edu.in' => true, //  India
  'edu.jm' => true, //  Jamaica
  'edu.jo' => true, //  Jordan
  'edu.kz' => true, //  Kazakhstan
  'edu.lb' => true, //  Lebanon
  'edu.ly' => true, //  Libya
  'edu.mo' => true, //  Macau
  'edu.my' => true, //  Malaysia
  'edu.mt' => true, //  Malta
  'edu.mx' => true, //  Mexico
  'edu.mm' => true, //  Myanmar
  'edu.np' => true, //  Nepal
  'edu.ni' => true, //  Nicaragua
  'edu.ng' => true, //  Nigeria
  'edu.kp' => true, //  North Korea
  'edu.om' => true, //  Oman
  'edu.pk' => true, //  Pakistan
  'edu.pe' => true, //  Peru
  'edu.ph' => true, //  Philippines
  'edu.pl' => true, //  Poland
  'edu.qa' => true, //  Qatar
  'edu.sa' => true, //  Saudi Arabia
  'edu.rs' => true, //  Serbia
  'edu.sg' => true, //  Singapore
  'edu.so' => true, //  Somalia
  'edu.za' => true, //  South Africa
  'edu.es' => true, //  Spain
  'edu.lk' => true, //  Sri Lanka
  'edu.sd' => true, //  Sudan
  'edu.tw' => true, //  Taiwan
  'edu.tr' => true, //  Turkey
  'edu.ua' => true, //  Ukraine
  'edu.uy' => true, //  Uruguay
  'edu.vn' => true, //  Vietnam

  'ernet.in' => true, //  India
  'res.in' => true, //  India

  // Goverment Entities
  'gov' => true, //  America
  'gov.af' => true, //  Afghanistan
  'gov.al' => true, //  Albania
  'gov.dz' => true, //  Algeria
  'gov.ad' => true, //  Andorra
  'gov.ao' => true, //  Angola
  'gov.am' => true, //  Armenia
  'gov.aw' => true, //  Aruba
  'gob.ar' => true, //  Argentina
  'gov.ar' => true, //  Argentina
  'gov.au' => true, //  Australia
  'gov.ax' => true, //  Åland Islands
  'gov.az' => true, //  Azerbaijan
  'gov.bs' => true, //  Bahamas
  'gov.bd' => true, //  Bangladesh
  'gov.bb' => true, //  Barbados
  'gov.by' => true, //  Belarus
  'gov.be' => true, //  Belgium
  'gov.bg' => true, //  Bulgaria
  'gov.ba' => true, //  Bosnia & Herzegovina
  'gov.br' => true, //  Brazil
  'gob.cl' => true, //  Chile
  'gov.cl' => true, //  Chile
  'gov.cn' => true, //  Mainland China
  'gov.hk' => true, //  Hong Kong
  'gov.mo' => true, //  Macau
  'gov.co' => true, //  Colombia
  'gov.cy' => true, //  Cyprus
  'gov.cz' => true, //  Czechia
  'gov.eg' => true, //  Egypt
  'gob.sv' => true, //  El Salvador
  'gov.gr' => true, //  Greece
  'gov.fi' => true, //  Finland
  'gouv.fr' => true, //  France
  'gov.hu' => true, //  Hungary
  'gov.in' => true, //  India
  'go.id' => true, //  Indonesia
  'gov.ir' => true, //  Iran
  'gov.iq' => true, //  Iraq
  'gov.krd' => true, //  Kurdistan Region
  'gov.ie' => true, //  Ireland
  'gov.il' => true, //  Israel
  'gov.it' => true, //  Italy
  'go.jp' => true, //  Japan
  'gov.kz' => true, //  Kazakhstan
  'go.ke' => true, //  Kenya
  'gov.lv' => true, //  Latvia
  'gov.lt' => true, //  Lithuania
  'gov.my' => true, //  Malaysia
  'gov.mt' => true, //  Malta
  'gob.mx' => true, //  Mexico
  'gov.md' => true, //  Moldova
  'gov.ma' => true, //  Morocco
  'gov.mm' => true, //  Myanmar
  'gov.np' => true, //  Nepal
  'govt.nz' => true, //  NewZealand
  'gov.ng' => true, //  Nigeria
  'gob.pe' => true, //  Peru
  'gov.pk' => true, //  Pakistan
  'gov.ph' => true, //  Philippines
  'gov.pl' => true, //  Poland
  'gov.pt' => true, //  Portugal
  'gov.ro' => true, //  Romania
  'gov.ru' => true, //  Russia
  'gov.sn' => true, //  Senegal
  'gov.sg' => true, //  Singapore
  'gov.sk' => true, //  Slovakia
  'gov.si' => true, //  Slovenia
  'go.kr' => true, //  South Korea
  'gob.es' => true, //  Spain
  'gov.lk' => true, //  Sri Lanka
  'gov.se' => true, //  Sweden
  'admin.ch' => true, //  Switzerland
  'gov.tw' => true, //  Taiwan
  'go.th' => true, //  Thailand
  'gov.tt' => true, //  Trinidad & Tobago
  'gov.tr' => true, //  Turkey
  'gov.ua' => true, //  Ukraine
  'gov.uk' => true, //  United Kingdom
  'gov.scot' => true, //  Scotland
  'gov.wales' => true, //  Wales
  'gov.gg' => true, //  Guernsey
  'gov.je' => true, //  Jersey
  'gov.im' => true, //  Isle of Man
  'gov.ai' => true, //  Anguilla
  'gov.bm' => true, //  Bermuda
  'gov.vg' => true, //  British Virgin Islands
  'gov.ky' => true, //  Cayman Islands
  'gov.fk' => true, //  Falkland Islands
  'government.pn' => true, //  Pitcairn Islands
  'gov.tc' => true, //  Turks & Caicos Islands
  'gub.uy' => true, //  Uruguay
  'gob.ve' => true, //  Venezuela
  'gov.vn' => true, //  Vietnam

  // Canada Federal Government
  'gc.ca' => true,
  'canada.ca' => true,

  // Canada Provinces
  'gov.ab.ca' => true, //  Alberta
  'gov.bc.ca' => true, //  British Columbia
  'gov.mb.ca' => true, //  Manitoba
  'gnb.ca' => true, //  New Brunswick
  'gov.nl.ca' => true, //  Newfoundland and Labrador
  'novascotia.ca' => true, //  Nova Scotia
  'ontario.ca' => true, //  Ontario
  'gov.pe.ca' => true, //  Prince Edward Island
  'gouv.qc.ca' => true, //  Quebec (French)
  'gov.sk.ca' => true, //  Saskatchewan

  // Canada Territories
  'gov.nt.ca' => true, //  Northwest Territories
  'gov.nu.ca' => true, //  Nunavut
  'gov.yk.ca' => true, //  Yukon

  // Military
  'mil' => true, //  United States
  'mod.uk' => true, //  United Kingdom
  'mil.uk' => true, //  United Kingdom
  'mod.gov.in' => true, //  India
  'mil.in' => true, //  India
  'mil.kr' => true, //  South Korea
  'mil.kz' => true, //  Kazakhstan
  'mil.jo' => true, //  Jordan
  'mil.kh' => true, //  Cambodia
  'mil.kw' => true, //  Kuwait
  'mil.lv' => true, //  Latvia
  'mil.my' => true, //  Malaysia
  'mil.mg' => true, //  Madagascar
  'mil.mn' => true, //  Mongolia
  'mil.mz' => true, //  Mozambique
  'mil.tz' => true, //  Tanzania

  // National Registries & Internet Authorities
  'nic.in' => true, //  Reserved by National Informatics Centre of India
  'nic.uk' => true, //  Reserved for Nominet UK for internal registry operations
  'nic.mx' => true, //  Reserved for NIC Mexico
  'nic.br' => true, //  Operated by NIC.br, the registry for Brazil and infrastructure control
  'nic.sg' => true, //  Reserved by SGNIC, Singapore’s domain registry
  'nic.id' => true, //  Reserved for Indonesia Network Information Centre (IDNIC)
  'nic.jp' => true, //  Reserved by JPNIC, Japan Network Information Center
  'nic.kr' => true, //  Reserved by KISA / Korea NIC (South Korea)
  'nic.vn' => true, //  Reserved for VNNIC, Vietnam Network Information Center
  'nic.cn' => true, //  Reserved by CNNIC, China Internet Network Information Center
];
