<?php

declare(strict_types=1);

return array (
  'login' => 'auth',
  'signin' => 'auth',
  'signon' => 'auth',
  'authenticate' => 'auth',
  'securelogin' => 'auth',
  'sign' => 'auth',
  'user' => 'auth',
  'session' => 'auth',
  'passcode' => 'auth',
  'access' => 'auth',
  'token' => 'auth',
  'account' => 'account',
  'verify' => 'account',
  'update' => 'account',
  'reset' => 'account',
  'recovery' => 'account',
  'unlock' => 'account',
  'validate' => 'account',
  'approval' => 'account',
  'credentials' => 'account',
  'secure' => 'security',
  'security' => 'security',
  'alert' => 'security',
  'warning' => 'security',
  'notice' => 'security',
  'paypal' => 'finance',
  'banking' => 'finance',
  'wallet' => 'finance',
  'billing' => 'finance',
  'invoice' => 'finance',
  'transaction' => 'finance',
  'payment' => 'finance',
  'webscr' => 'finance',
  'support' => 'support',
  'helpdesk' => 'support',
  'contact' => 'support',
  'service' => 'support',
  'customer' => 'support',
);
